server:
  port: 8080

spring:
  application:
    name: Store-Finder
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        spatial:
          database: POSTGIS

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

store-finder:
  data:
    json:
      stores-info: db/data/stores.json
  openapi:
    dev-url: http://localhost:8080
    prod-url: http://localhost:8080
  jwt:
    secret: e9e89c1617bcdb279ec7999677232ea9ee67f9da3666f818f3d6f5d0806c77c7
    expiration-in-milliseconds: 600000
  env:
    jasypt-encryptor-password: jasypt-itest
  security:
    cors-allowed-origins: http://localhost:8080,http://localhost:3000
